<template>
    <v-app>
        <v-main>
            <v-container>
                <v-row>
                    <v-col>
                        Home
                    </v-col>
                </v-row>
            </v-container>
        </v-main>
    </v-app>
</template>